title: RESPIRA Fiware
description: Open FIWARE air monitoring device for urban applications

theme: jekyll-theme-primer

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

