title: RESPIRA FIWARE
description: Open FIWARE air monitoring device and platform for urban applications

theme: jekyll-theme-primer

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

languages: ["en", "es"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  es: Spanish
  en: English
